### ISSUE TITLE
折线图点击时会影响下面的按钮布局，松开就会恢复原位

### ISSUE THREAD

**Issue by YunShang521** [rongcheng2017/f_line_chart#2]
![image](https://user-images.githubusercontent.com/95212630/164591217-dd24718b-8915-4d09-afd2-9425c5e1378e.png)

**Comment by YunShang521** [comment]
![image](https://user-images.githubusercontent.com/95212630/164591346-39c1151c-6532-4495-a97a-358bd0de4aa7.png)

**Comment by rongcheng2017** [comment]
use 1.0.8 , fixed this issuse
